version: '3.6'

services:
  ## Define telegraf service
  ia_telegraf:
    depends_on:
      - ia_common
    build:
      context: $PWD/../Telegraf
      dockerfile: $PWD/../Telegraf/Dockerfile
      args:
        EIS_VERSION: ${EIS_VERSION}
        EIS_UID: ${EIS_UID}
        TELEGRAF_VERSION: ${TELEGRAF_VERSION}
    container_name: ia_telegraf
    hostname: ia_telegraf
    network_mode: host
    image: ${DOCKER_REGISTRY}ia_telegraf:${EIS_VERSION}
    restart: unless-stopped
    environment:
      AppName: "Telegraf"
      InfluxDbAppName: "InfluxDBConnector"
      CertType: ""
      DEV_MODE: ${DEV_MODE}
      no_proxy: ${eis_no_proxy},${ETCD_HOST}
      NO_PROXY: ${eis_no_proxy},${ETCD_HOST}
      ETCD_HOST: ${ETCD_HOST}
      HOST_IP: '127.0.0.1'
      INFLUX_SERVER: '127.0.0.1'
      INFLUXDB_PORT: $INFLUXDB_PORT
      ETCD_PREFIX: ${ETCD_PREFIX}
    user: ${EIS_UID}
    secrets:
      - ca_etcd
      - etcd_InfluxDBConnector_cert
      - etcd_InfluxDBConnector_key

secrets:
  etcd_InfluxDBConnector_cert:
    file: provision/Certificates/InfluxDBConnector/InfluxDBConnector_client_certificate.pem
  etcd_InfluxDBConnector_key:
    file: provision/Certificates/InfluxDBConnector/InfluxDBConnector_client_key.pem